CREATE DATABASE T_Peoples;

USE T_Peoples;

CREATE TABLE Funcionarios(
		IdFuncionarios	INT PRIMARY KEY IDENTITY
		,Nome		VARCHAR (255) NOT NULL UNIQUE
		,Sobrenome		VARCHAR (255) NOT NULL UNIQUE
);


